title: Priti Desai's Notes

email: pdesai@us.ibm.com

description: > # this means to ignore newlines until "baseurl:"
  A collection of my published/unpublished notes.

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: PritiDesai8

github_username:  pritidesai

baseurl: ""
sass: 
    style: compressed


# Tracker
analytics: UA-83979019-1


exclude:
- README.md

include: 
- _pages
